<?php

return [
    1 => 'Université Internationale de Rabat (UIR)',
    2 => 'Université Mohammed VI des Sciences de Santé (UM6SS) - Casablanca',
    3 => 'Université Internationale Abulcasis des Sciences de Santé (UIASS) - Rabat',
    4 => 'Université Euro-méditerranéenne de Fès (UEMF)',
    5 => 'Université Mohammed VI Polytechnique (UM6P) - Ben Guérir',
    6 => 'Université Privée Marrakech Tensift El Haouz (UPM)',
    7 => 'Université Internationale d\'Agadir - Universiapolis',
    8 => 'Université Internationale de Casablanca (UIC)',
    9 => 'École Supérieure d\'Architecture de Casablanca (EAC)',
    10 => 'École Centrale de Casablanca (ECC)',
    11 => 'ESCA École de Management',
    12 => 'Université Privée Mundiapolis - Casablanca',
    13 => 'Université Privée de Fès (UPF)',
    14 => 'Sup de Co - École Supérieure de Commerce - Marrakech',
    15 => 'École Supérieure en Ingénierie de l\'Information, Télécoms, Management et Génie Civil (ESTEM) - Casablanca',
    16 => 'Institut Supérieur du Génie Appliqué Casablanca (IGA)',
    17 => 'École Marocaine des Sciences de l\'Ingénieur - Casablanca (EMSI-Casablanca)',
    18 => 'École Marocaine des Sciences de l\'Ingénieur - Rabat (EMSI-Rabat)',
    19 => 'École Marocaine des Sciences de l\'Ingénieur - Marrakech (EMSI-Marrakech)',
    20 => 'Institut Supérieur d\'Ingénierie et des Affaires - Rabat (ISGA-Rabat)',
    21 => 'Institut Supérieur d\'Ingénierie et des Affaires - Fès (ISGA-Fès)',
    22 => 'Institut Supérieur d\'Ingénierie et des Affaires - Marrakech (ISGA-Marrakech)',
    23 => 'École Marocaine d\'Ingénierie (EMG-Rabat)',
    24 => 'Institut Supérieur de Transport et de la Logistique (ISTL) - Casablanca',
    25 => 'Institut des Hautes Études de Management (HEM) - Casablanca',
    26 => 'École des Hautes Études Économiques, Commerciales et d\'Ingénierie (HEEC) - Marrakech',
    27 => 'École Supérieure de Management de Commerce et d\'Informatique (SUP\'MANAGEMENT) - Fès',
    28 => 'International Institute for Higher Education in Morocco (IIHEM) - Rabat',
    29 => 'École d\'Ingénierie en Génie des Systèmes Industriels de Casablanca (EIGSICA)',
    30 => 'École Supérieure de Management, Informatique et Télécommunication (SUPMTI) - Rabat',
    31 => 'École des Hautes Études d\'Ingénierie (EHEIO) - Oujda',
    32 => 'École de Management et d\'Administration des Affaires - Agadir',
    33 => 'Institut Supérieur d\'Ingénierie et des Affaires (ISGA-Casablanca)',
    34 => 'Institut Supérieur de Management, d\'Administration et de Génie Informatique (ISMAGI)',
    35 => 'Écoles des Hautes Études en Sciences et Techniques de l\'Ingénierie et du Management Privée (HESTIM)',
    36 => 'École des Hautes Études Commerciales et Informatiques - Casablanca (HECI-Casablanca)',
    37 => 'École Supérieure des Sciences Économiques et de Management (ESSEM)',
    38 => 'École Supérieure de Management et de Gestion des Ressources Humaines (SUP\'RH)',
    39 => 'École Supérieure des Sciences de Santé (ESSS) - Casablanca',
    40 => 'École des Nouvelles Sciences et Ingénierie (ENSIT) - Tanger',
    41 => 'Écoles Marocaines des Sciences de l\'Ingénieur en Informatique Industrielle et Informatique de Gestion (EMSI-Tanger)',
    42 => 'École Privée des Hautes Études Comptables et Financières (HECF) - Fès',
];
